export type Language = "en" | "ur";

export const UI_COPY = {
  en: {
    brandSubtitle: "A public model-behavior study",
    nav: { aria: "Primary navigation", contribute: "Contribute", results: "Results", methodology: "Methodology" },
    intro: {
      eyebrow: "Open public benchmark",
      headline: "Does the same AI reason differently across borders?",
      lede: "Run 15 fixed, culturally neutral prompts in the AI product you already use. Your verbatim results help test whether the same declared model and plan behave differently by location.",
      start: "Start the benchmark",
      seeResults: "See public results",
      factsAria: "Benchmark facts",
      facts: [["About 20 minutes", "One fresh chat per prompt"], ["15 prompts", "13 scored + 2 unscored probes"], ["City and country", "No exact address or raw IP stored"]],
      heroAlt: "Pastel sketch of people in different cities sending the same prompts to an AI service for comparison.",
      hypothesis: "The same model label and plan may still produce different effective behavior by location.",
      disclaimer: "This measures observed variation. It cannot by itself prove model substitution, intent, or cause.",
      whyEyebrow: "Research purpose",
      whyTitle: "Why we collect this data",
      whyBody: [
        "AI companies serve their chat products worldwide, but users in different countries sometimes report different quality from the “same” model. This project measures that claim instead of speculating about it. You run a fixed set of reasoning questions through your AI chat app and paste the responses here.",
        "We combine submissions from many cities to check whether accuracy, response length, rough response time, and the model’s own self-description differ by location for the same model and plan. We store your city and country, the product setup you report, the model responses, and rough timing. We do not ask for your name, email, account details, or exact address; do not include them in any field or pasted response. Results are published only in aggregate for groups of at least five submissions. The goal is public evidence about whether everyone, everywhere, gets the same AI they are paying for.",
      ],
      guideEyebrow: "How to contribute",
      guideTitle: "Three simple actions, repeated carefully",
      guideAlt: "Pastel sketch showing a prompt copied from this benchmark, asked in a fresh AI chat, then pasted back verbatim.",
      guideSteps: ["Copy the fixed prompt", "Ask it in a fresh chat", "Paste the first complete response"],
    },
    setup: {
      eyebrow: "Before you begin",
      title: "Describe the test you will actually run.",
      lede: "Every field below helps us compare like with like. Choose what is true, even when it differs from the primary protocol.",
      where: "Where are you running the test?",
      countryLabel: "Country or territory",
      countryPlaceholder: "Choose an ISO country or territory",
      cityLabel: "City or nearest large city",
      cityPlaceholder: "e.g. Washington",
      cityNote: "Do not enter an address, neighborhood, postal code, or coordinates.",
      modelQuestion: "Which AI product are you testing?",
      providerLabel: "AI service or product",
      modelLabel: "Model label shown in the product",
      choose: "Choose one",
      exactModel: "Exact model label",
      exactPlaceholder: "Copy the label exactly as shown",
      accessQuestion: "What access and plan are you using?",
      planLabel: "Plan label",
      planPlaceholder: "e.g. Plus, Pro, Team, API, or Free",
      configurationQuestion: "Record the test configuration",
      configurationNote: "Primary protocol target: English product UI, no VPN, memory and custom instructions off, prompts not translated, and completion in one sitting. Select what is actually true.",
      uiLanguage: "Tested product UI language",
      platform: "Platform",
      reasoningToggle: "Reasoning / thinking toggle",
      vpnUsed: "VPN used",
      memoryPersonalization: "Memory / personalization",
      customInstructions: "Custom instructions",
      promptsTranslated: "Were the prompts translated?",
      completedInOneSitting: "Will this run be completed in one sitting?",
      primaryTarget: "Primary protocol",
      requiredChoice: "Choose truthfully",
      consentTitle: "I understand the study and consent to contribute this run.",
      consentText: "This project collects my city/country, reported product configuration, verbatim model responses, rough timing, and unverified model self-reports to test location-linked behavior. It does not ask for my name, email, account details, or exact address, and I will not include them in any field or pasted response. Raw IP is never stored: it is processed only transiently into an unlinkable daily HMAC counter for anti-abuse, then discarded. Public results appear only as aggregates for groups of at least five submissions.",
      continue: "Begin the prompts",
      privacyTitle: "Privacy is part of the benchmark design.",
      privacyItems: ["Name, email, sign-in, and account ID are not requested", "No GPS or exact address is requested", "Raw model responses never appear in public results", "Raw IP is never stored", "Public cells require at least five submissions"],
      privacyNote: "For anti-abuse, the server processes the connection IP transiently into an unlinkable daily HMAC counter. The raw IP is immediately discarded and never enters the research database.",
      optionLabels: {
        uiLanguage: { en: "English", ur: "Urdu", other: "Another language" },
        platform: { web: "Web browser", ios: "iOS app", android: "Android app", desktop: "Desktop app" },
        reasoningToggle: { on: "On", off: "Off", unavailable: "Unavailable", unsure: "Unsure" },
        vpnUsed: { no: "No", yes: "Yes", unsure: "Unsure" },
        configuration: { off: "Off", on: "On", unsure: "Unsure" },
        binary: { "0": "No", "1": "Yes" },
      },
    },
    runner: {
      yourTest: "Your test",
      rulesTitle: "Keep each item comparable",
      rules: ["Open a fresh chat for every prompt.", "Use the first response only; do not edit or regenerate.", "Copy each English prompt unchanged.", "Paste the complete response, including the REASONING TOKENS line.", "Record the rough response time truthfully."],
      question: "Prompt",
      of: "of",
      complete: "complete",
      variant: "Session variant",
      unscored: "Unscored probe",
      fixedNotice: "Copy this fixed English prompt exactly. Its final token line asks the model for an unverified self-report, not a measured token count.",
      copyPrompt: "Copy complete prompt",
      defaultStatus: "Paste it into a fresh chat, then return the first complete response here.",
      copied: "Complete prompt copied, including the reasoning-token trailer.",
      blocked: "Automatic copy was blocked. Select the entire prompt and copy it manually.",
      responseLabel: "Paste the model’s complete first response",
      responsePlaceholder: "Include all visible explanation, refusal or error text, and the final REASONING TOKENS line.",
      tokenNotice: "Any reasoning-token value is self-reported by the model, not verified. Do not submit a run if a pasted response contains personal information.",
      shortWarning: "This looks unusually short. A refusal or error is valid, but paste it in full.",
      responseTime: "Rough response time",
      responseTimePlaceholder: "Choose a required time bucket",
      regenerated: "This response was regenerated or followed an edited prompt.",
      responseControlsHint: "Required for every prompt",
      back: "Back",
      next: "Next prompt",
      review: "Review responses",
      timeOptions: { lt5: "Under 5 seconds", "5to15": "5–15 seconds", "15to60": "15–60 seconds", gt60: "Over 60 seconds" },
    },
    review: {
      eyebrow: "Final check",
      title: "Your contribution is ready.",
      lede: "Scoring happens only on the server. Expected answers are not sent to this page.",
      record: "Benchmark record",
      location: "Location",
      provider: "Service",
      model: "Model",
      access: "Access",
      configuration: "Configuration",
      responses: "Responses",
      edit: "Edit setup",
      improve: "Help improve",
      feedback: "Optional feedback",
      clarity: "Were the prompts clear?",
      attention: "Which prompt needs attention?",
      none: "None / skip",
      why: "Why?",
      anonymous: "Anonymous, aggregate-first publication",
      privateNote: "Raw responses are never published. Group results appear only after at least five eligible submissions match the comparison cell.",
      turnstileTitle: "Anti-abuse verification",
      turnstilePrompt: "Complete Cloudflare’s privacy-preserving check before submitting.",
      turnstileLoading: "Loading verification…",
      turnstileUnavailable: "Verification is unavailable. Refresh or try again shortly.",
      turnstileVerified: "Verification complete.",
      turnstileRequired: "Verification is required before submission.",
      submitting: "Submitting…",
      submit: "Submit anonymously",
    },
    success: {
      eyebrow: "Contribution received",
      title: "Your run is now part of the benchmark.",
      score: "Objective reasoning score",
      privatePrefix: "Your model’s raw responses remain private. An aggregate result for",
      privateSuffix: "appears only after the privacy threshold is reached.",
      excluded: "This run was stored, but its reported setup falls outside the primary analysis protocol and it will not contribute to the public aggregate.",
      results: "View aggregate results",
      home: "Return home",
    },
    results: {
      eyebrow: "Public aggregate results",
      title: "Look for patterns, not rankings.",
      lede: "These comparisons show observed behavior under self-reported conditions. They do not prove that location caused a difference or that a provider substituted a model.",
      versionLabel: "Benchmark version",
      versions: { "core-2.0": "core-2.0 · current", "core-1.0": "core-1.0 · archived" },
      loading: "Loading aggregate results…",
      unavailable: "Results are not ready yet.",
      stats: ["eligible contributions", "reported cities", "declared models", "display threshold"],
      emptyTitle: "No comparison has reached the privacy threshold yet.",
      emptyText: "Be one of the first contributors. A matching country/city/model/access cell appears after five eligible runs.",
      contribute: "Contribute a run",
      headers: ["City / country", "Declared model", "Access", "Runs", "Reasoning score"],
      exploratory: "exploratory",
      descriptive: "Descriptive mean; no confidence interval is shown.",
      scoreBasis: "For core-2.0, the score uses 13 objective items per run; the two probes are excluded.",
      read: "Read this carefully",
      interpretation: "A difference is evidence of behavioral variation—not proof of a different backend model. Compare only the same provider, declared model, access type, plan, and benchmark version.",
    },
    methodology: {
      eyebrow: "Methodology · capability ruler",
      title: "A controlled public experiment, made stronger together.",
      lede: "The benchmark tests whether behavior differs by participant-reported location while the provider, model label, plan, and protocol are held as constant as practical.",
      cards: [
        ["What is measured", "Fifteen culturally neutral prompts form a difficulty ladder: 13 objectively scored items and two unscored probes for model self-description and response style."],
        ["What is stored", "Country/city, product and protocol metadata, prompt order and variant, complete model outputs, rough timing, unverified token self-reports, derived scores, and optional feedback."],
        ["What stays private", "Raw outputs never appear in public results. Names, emails, account identifiers, and exact addresses are not requested; participants are instructed not to include them. Raw IP is never stored and is processed only transiently into an unlinkable daily HMAC anti-abuse counter."],
        ["How scoring works", "Versioned objective server rules score 13 items; M1 and M2 remain unscored. Public cells require five eligible submissions, and cells below thirty are labeled exploratory."],
      ],
      guidelinesEyebrow: "Participant protocol",
      guidelinesTitle: "Follow these rules for the most useful response.",
      guidelinesIntro: "Accuracy matters more than appearing protocol-perfect. If something differs, record it honestly; the run is stored and flagged rather than silently rewritten.",
      guidelineGroups: [
        ["Before", ["Use the exact model label and plan shown in the product.", "Set memory/personalization and custom instructions off.", "Do not use a VPN; if one is active, report it honestly.", "Use the English product UI and note the reasoning/thinking-toggle state."]],
        ["During", ["Open a fresh chat for every prompt.", "Use the copy button; never retype, edit, or translate a prompt.", "Use only the first response—do not regenerate, edit, ask “are you sure?”, or follow up.", "Paste the entire response verbatim, including visible reasoning and the REASONING TOKENS line.", "Record the rough time bucket and complete all prompts in one sitting."]],
        ["After", ["Optionally repeat the full run 24–48 hours later with the same configuration.", "Do not publish or discuss the prompts or answers publicly; answer leakage contaminates future data."]],
      ],
      disqualifiersTitle: "Stored but excluded from primary analysis",
      disqualifiers: ["Any regenerated response", "A non-English tested-product UI", "VPN use or an unknown VPN state", "Memory/personalization or custom instructions on or unknown", "Translated prompts", "A run spread across multiple days"],
      tokenNote: "The model cannot reliably inspect its own hidden reasoning-token use. Any number it supplies is an unverified self-report and is never presented as a measured token count.",
      limits: "Limits of the evidence",
      limitsTitle: "This can identify a pattern. It cannot establish intent.",
      limitations: ["Country and city are self-reported and unverified.", "Participants are a convenience sample.", "Manual copy/paste can introduce errors.", "People may contribute more than once.", "Billing region and account history remain uncontrolled.", "Providers update models and run experiments.", "Models are nondeterministic.", "English prompts may interact with locale settings."],
      improve: "Help improve the evidence",
      cta: "Every careful, honestly documented run makes the comparison more useful.",
      run: "Run the benchmark",
    },
    footer: { left: "Reasoning Across Borders · Independent public benchmark", right: "No sign-in · No raw IP stored · Aggregate results only" },
    errors: {
      results: "Results are unavailable.",
      location: "Choose a country and enter a city or nearest large city—not an address or neighborhood.",
      fields: "Complete the provider, model, access, and plan fields.",
      protocol: "Choose a truthful value for every configuration field.",
      consent: "Confirm that you understand and consent to the study.",
      session: "A secure benchmark session could not be started. Please try again.",
      save: "Your contribution could not be saved.",
    },
    access: {
      Free: ["Free", "No recurring payment"],
      Paid: ["Paid", "Personal, work, or API payment"],
      "Not sure": ["Not sure", "The product does not make this clear"],
    },
    accessTypes: ["Free individual access", "Paid individual access", "Education or research access", "Work or team access", "Enterprise access", "Not sure"],
    clarity: ["Skip this question", "Very unclear", "Often unclear", "Mixed", "Mostly clear", "Very clear"],
    feedback: { "": "Skip this question", unclear: "unclear", "answer disputed": "answer disputed", "technical issue": "technical issue", "too long": "too long" },
  },
  ur: {
    brandSubtitle: "ماڈل کے رویّے کا عوامی مطالعہ",
    nav: { aria: "مرکزی فہرست", contribute: "حصہ لیں", results: "نتائج", methodology: "طریقۂ کار" },
    intro: {
      eyebrow: "عوام کے لیے کھلا بینچ مارک",
      headline: "کیا ایک ہی اے آئی مختلف جگہوں پر مختلف انداز سے سوچتا ہے؟",
      lede: "اپنے زیرِ استعمال اے آئی پروڈکٹ میں پندرہ مقررہ اور ثقافتی طور پر غیر جانب دار سوالات چلائیں۔ آپ کے لفظ بہ لفظ نتائج سے جانچا جائے گا کہ ایک ہی بتائے گئے ماڈل اور پلان کا رویّہ جگہ کے لحاظ سے بدلتا ہے یا نہیں۔",
      start: "بینچ مارک شروع کریں",
      seeResults: "عوامی نتائج دیکھیں",
      factsAria: "بینچ مارک کی تفصیل",
      facts: [["تقریباً ۲۰ منٹ", "ہر سوال کے لیے نئی چیٹ"], ["۱۵ سوال", "۱۳ اسکور شدہ + ۲ بغیر اسکور کے جائزے"], ["شہر اور ملک", "درست پتہ یا خام IP محفوظ نہیں"]],
      heroAlt: "نرم رنگوں کا خاکہ جس میں مختلف شہروں کے لوگ موازنے کے لیے ایک ہی سوال اے آئی سروس کو بھیج رہے ہیں۔",
      hypothesis: "ایک ہی ماڈل لیبل اور پلان کے باوجود مختلف جگہوں پر مؤثر رویّہ بدل سکتا ہے۔",
      disclaimer: "یہ صرف نظر آنے والے فرق کو ناپتا ہے؛ اس سے ماڈل کی تبدیلی، ارادہ یا وجہ خود بخود ثابت نہیں ہوتی۔",
      whyEyebrow: "تحقیق کا مقصد",
      whyTitle: "ہم یہ معلومات کیوں جمع کرتے ہیں",
      whyBody: [
        "اے آئی کمپنیاں اپنی چیٹ مصنوعات دنیا بھر میں فراہم کرتی ہیں، مگر مختلف ملکوں کے صارفین کبھی کبھار ’اسی‘ ماڈل کے معیار میں فرق بتاتے ہیں۔ یہ منصوبہ قیاس کے بجائے اس دعوے کو ناپتا ہے۔ آپ اپنی اے آئی چیٹ ایپ میں استدلال کے مقررہ سوالات چلاتے اور مکمل جواب یہاں پیسٹ کرتے ہیں۔",
        "ہم مختلف شہروں سے آنے والے اندراج ملا کر دیکھتے ہیں کہ ایک ہی ماڈل اور پلان میں درستگی، جواب کی لمبائی، اندازاً وقت، اور ماڈل کا اپنا تعارف جگہ کے لحاظ سے بدلتے ہیں یا نہیں۔ ہم آپ کا شہر و ملک، آپ کی بتائی ہوئی ترتیب، جوابات اور اندازاً وقت محفوظ کرتے ہیں۔ ہم نام، ای میل، اکاؤنٹ کی تفصیل یا درست پتہ نہیں مانگتے؛ انہیں کسی خانے یا پیسٹ کیے گئے جواب میں شامل نہ کریں۔ نتائج صرف کم از کم پانچ اندراج والے مجموعی گروہوں میں شائع ہوتے ہیں۔ مقصد عوامی ثبوت ہے کہ کیا ہر جگہ لوگوں کو وہی اے آئی ملتی ہے جس کی وہ قیمت دیتے ہیں۔",
      ],
      guideEyebrow: "حصہ لینے کا طریقہ",
      guideTitle: "تین آسان کام، ہر بار احتیاط سے",
      guideAlt: "نرم رنگوں کا خاکہ: سوال یہاں سے کاپی کریں، نئی اے آئی چیٹ میں پوچھیں، پھر پہلا مکمل جواب جوں کا توں پیسٹ کریں۔",
      guideSteps: ["مقررہ سوال کاپی کریں", "نئی چیٹ میں پوچھیں", "پہلا مکمل جواب پیسٹ کریں"],
    },
    setup: {
      eyebrow: "شروع کرنے سے پہلے",
      title: "جو ٹیسٹ آپ واقعی کریں گے اس کی تفصیل دیں۔",
      lede: "ہر خانہ یکساں حالات کا موازنہ کرنے میں مدد دیتا ہے۔ اصل صورت منتخب کریں، خواہ وہ بنیادی طریقۂ کار سے مختلف ہو۔",
      where: "آپ ٹیسٹ کہاں چلا رہے ہیں؟",
      countryLabel: "ملک یا علاقہ",
      countryPlaceholder: "ISO ملک یا علاقہ منتخب کریں",
      cityLabel: "شہر یا قریب ترین بڑا شہر",
      cityPlaceholder: "مثلاً لاہور",
      cityNote: "گھر کا پتہ، محلہ، پوسٹل کوڈ یا نقشے کے نقاط درج نہ کریں۔",
      modelQuestion: "آپ کون سا اے آئی پروڈکٹ جانچ رہے ہیں؟",
      providerLabel: "اے آئی سروس یا پروڈکٹ",
      modelLabel: "پروڈکٹ میں دکھایا گیا ماڈل",
      choose: "ایک منتخب کریں",
      exactModel: "ماڈل کا بالکل درست نام",
      exactPlaceholder: "دکھایا گیا نام جوں کا توں لکھیں",
      accessQuestion: "آپ کس رسائی اور پلان پر ہیں؟",
      planLabel: "پلان کا نام",
      planPlaceholder: "مثلاً Plus، Pro، Team، API یا Free",
      configurationQuestion: "ٹیسٹ کی ترتیب درج کریں",
      configurationNote: "بنیادی طریقۂ کار: پروڈکٹ کا انگریزی UI، VPN بند، یادداشت اور ذاتی ہدایات بند، سوالات کا ترجمہ نہیں، اور ایک ہی نشست۔ جو حقیقت ہے وہی منتخب کریں۔",
      uiLanguage: "جانچے گئے پروڈکٹ کے UI کی زبان",
      platform: "پلیٹ فارم",
      reasoningToggle: "استدلال / تھنکنگ کا اختیار",
      vpnUsed: "VPN استعمال ہوا",
      memoryPersonalization: "یادداشت / ذاتی ترتیب",
      customInstructions: "ذاتی ہدایات",
      promptsTranslated: "کیا سوالات کا ترجمہ ہوا؟",
      completedInOneSitting: "کیا ٹیسٹ ایک ہی نشست میں مکمل ہوگا؟",
      primaryTarget: "بنیادی طریقۂ کار",
      requiredChoice: "سچائی سے منتخب کریں",
      consentTitle: "میں مطالعہ سمجھتا/سمجھتی ہوں اور اس ٹیسٹ کی شمولیت پر رضامند ہوں۔",
      consentText: "یہ منصوبہ جگہ سے منسلک رویّہ جانچنے کے لیے میرا شہر/ملک، بتائی ہوئی پروڈکٹ ترتیب، ماڈل کے مکمل جواب، اندازاً وقت اور ماڈل کے غیر مصدقہ خود بیان محفوظ کرتا ہے۔ یہ نام، ای میل، اکاؤنٹ کی تفصیل یا درست پتہ نہیں مانگتا، اور میں انہیں کسی خانے یا پیسٹ کیے گئے جواب میں شامل نہیں کروں گا/گی۔ خام IP کبھی محفوظ نہیں ہوتا؛ وہ صرف عارضی طور پر ایک ناقابلِ ربط روزانہ HMAC انسدادِ غلط استعمال شمار بنانے کے لیے استعمال ہو کر فوراً ضائع ہو جاتا ہے۔ عوامی نتائج صرف کم از کم پانچ اندراج والے مجموعی گروہوں میں آتے ہیں۔",
      continue: "سوالات شروع کریں",
      privacyTitle: "رازداری بینچ مارک کے ڈیزائن کا حصہ ہے۔",
      privacyItems: ["نام، ای میل، سائن اِن یا اکاؤنٹ ID نہیں مانگا جاتا", "GPS یا درست پتہ نہیں مانگا جاتا", "ماڈل کے خام جواب عوامی نتائج میں نہیں آتے", "خام IP کبھی محفوظ نہیں ہوتا", "عوامی گروہ کے لیے کم از کم پانچ اندراج"],
      privacyNote: "غلط استعمال روکنے کے لیے سرور رابطے کا IP عارضی طور پر ایک ناقابلِ ربط روزانہ HMAC شمار میں بدلتا ہے۔ خام IP فوراً ضائع ہو جاتا اور تحقیقی ڈیٹابیس میں کبھی داخل نہیں ہوتا۔",
      optionLabels: {
        uiLanguage: { en: "انگریزی", ur: "اردو", other: "کوئی دوسری زبان" },
        platform: { web: "ویب براؤزر", ios: "iOS ایپ", android: "Android ایپ", desktop: "ڈیسک ٹاپ ایپ" },
        reasoningToggle: { on: "چالو", off: "بند", unavailable: "دستیاب نہیں", unsure: "معلوم نہیں" },
        vpnUsed: { no: "نہیں", yes: "ہاں", unsure: "معلوم نہیں" },
        configuration: { off: "بند", on: "چالو", unsure: "معلوم نہیں" },
        binary: { "0": "نہیں", "1": "ہاں" },
      },
    },
    runner: {
      yourTest: "آپ کا ٹیسٹ",
      rulesTitle: "ہر سوال قابلِ موازنہ رکھیں",
      rules: ["ہر سوال کے لیے نئی چیٹ کھولیں۔", "صرف پہلا جواب استعمال کریں؛ ترمیم یا دوبارہ جواب نہ لیں۔", "ہر انگریزی سوال جوں کا توں کاپی کریں۔", "REASONING TOKENS سطر سمیت مکمل جواب پیسٹ کریں۔", "اندازاً وقت سچائی سے درج کریں۔"],
      question: "سوال",
      of: "از",
      complete: "مکمل",
      variant: "سیشن کی قسم",
      unscored: "بغیر اسکور کا جائزہ",
      fixedNotice: "اس مقررہ انگریزی سوال کو جوں کا توں کاپی کریں۔ آخری ٹوکن سطر ماڈل سے غیر مصدقہ خود بیان مانگتی ہے؛ یہ ناپا ہوا ٹوکن شمار نہیں۔",
      copyPrompt: "مکمل سوال کاپی کریں",
      defaultStatus: "اسے نئی چیٹ میں پیسٹ کریں، پھر پہلا مکمل جواب یہاں واپس لائیں۔",
      copied: "استدلالی ٹوکن کی آخری سطر سمیت مکمل سوال کاپی ہو گیا۔",
      blocked: "خودکار کاپی رک گئی۔ پورا سوال منتخب کر کے خود کاپی کریں۔",
      responseLabel: "ماڈل کا پہلا مکمل جواب پیسٹ کریں",
      responsePlaceholder: "تمام نظر آنے والی وضاحت، انکار یا غلطی، اور آخری REASONING TOKENS سطر شامل کریں۔",
      tokenNotice: "استدلالی ٹوکن کی ہر قدر ماڈل کا خود بیان ہے، مصدقہ نہیں۔ اگر پیسٹ کیے گئے جواب میں ذاتی معلومات ہوں تو ٹیسٹ جمع نہ کریں۔",
      shortWarning: "یہ جواب غیر معمولی طور پر مختصر لگتا ہے۔ انکار یا غلطی درست اندراج ہے، مگر اسے پورا پیسٹ کریں۔",
      responseTime: "جواب کا اندازاً وقت",
      responseTimePlaceholder: "وقت کی لازمی حد منتخب کریں",
      regenerated: "یہ جواب دوبارہ بنوایا گیا یا ترمیم شدہ سوال کے بعد آیا۔",
      responseControlsHint: "ہر سوال کے لیے ضروری",
      back: "واپس",
      next: "اگلا سوال",
      review: "جوابات دیکھیں",
      timeOptions: { lt5: "۵ سیکنڈ سے کم", "5to15": "۵–۱۵ سیکنڈ", "15to60": "۱۵–۶۰ سیکنڈ", gt60: "۶۰ سیکنڈ سے زیادہ" },
    },
    review: {
      eyebrow: "آخری جانچ",
      title: "آپ کا اندراج تیار ہے۔",
      lede: "اسکور صرف سرور پر بنتا ہے۔ درست جواب اس صفحے پر نہیں بھیجے جاتے۔",
      record: "بینچ مارک ریکارڈ",
      location: "جگہ",
      provider: "سروس",
      model: "ماڈل",
      access: "رسائی",
      configuration: "ترتیب",
      responses: "جوابات",
      edit: "ترتیب بدلیں",
      improve: "بہتری میں مدد",
      feedback: "اختیاری رائے",
      clarity: "کیا سوال واضح تھے؟",
      attention: "کس سوال کو توجہ چاہیے؟",
      none: "کوئی نہیں / چھوڑ دیں",
      why: "کیوں؟",
      anonymous: "گمنام، صرف مجموعی اشاعت",
      privateNote: "خام جواب کبھی شائع نہیں ہوتے۔ موازنے کا گروہ صرف کم از کم پانچ یکساں اور قابلِ استعمال اندراج کے بعد ظاہر ہوتا ہے۔",
      turnstileTitle: "غلط استعمال سے بچاؤ کی تصدیق",
      turnstilePrompt: "جمع کرانے سے پہلے Cloudflare کی رازداری دوست جانچ مکمل کریں۔",
      turnstileLoading: "تصدیق لوڈ ہو رہی ہے…",
      turnstileUnavailable: "تصدیق دستیاب نہیں۔ صفحہ تازہ کریں یا کچھ دیر بعد کوشش کریں۔",
      turnstileVerified: "تصدیق مکمل ہے۔",
      turnstileRequired: "جمع کرانے سے پہلے تصدیق ضروری ہے۔",
      submitting: "جمع ہو رہا ہے…",
      submit: "گمنام طور پر جمع کریں",
    },
    success: {
      eyebrow: "اندراج موصول ہو گیا",
      title: "آپ کا ٹیسٹ اب بینچ مارک کا حصہ ہے۔",
      score: "معروضی استدلال کا اسکور",
      privatePrefix: "ماڈل کے خام جواب نجی رہیں گے۔",
      privateSuffix: "کا مجموعی نتیجہ رازداری کی حد پوری ہونے کے بعد دکھے گا۔",
      excluded: "یہ ٹیسٹ محفوظ ہو گیا، مگر بتائی گئی ترتیب بنیادی تجزیاتی طریقۂ کار سے باہر ہے، اس لیے یہ عوامی مجموعی نتیجے میں شامل نہیں ہوگا۔",
      results: "مجموعی نتائج دیکھیں",
      home: "مرکزی صفحے پر واپس جائیں",
    },
    results: {
      eyebrow: "عوامی مجموعی نتائج",
      title: "رجحان دیکھیں، درجہ بندی نہیں۔",
      lede: "یہ موازنے شرکاء کی اپنی بتائی ہوئی حالتوں میں نظر آنے والا رویّہ دکھاتے ہیں۔ یہ ثابت نہیں کرتے کہ فرق جگہ کی وجہ سے ہوا یا سروس نے ماڈل بدل دیا۔",
      versionLabel: "بینچ مارک ورژن",
      versions: { "core-2.0": "core-2.0 · موجودہ", "core-1.0": "core-1.0 · محفوظ شدہ" },
      loading: "مجموعی نتائج لوڈ ہو رہے ہیں…",
      unavailable: "نتائج ابھی تیار نہیں۔",
      stats: ["قابلِ استعمال اندراج", "بتائے گئے شہر", "بتائے گئے ماڈل", "دکھانے کی کم از کم حد"],
      emptyTitle: "ابھی کوئی موازنہ رازداری کی حد تک نہیں پہنچا۔",
      emptyText: "ابتدائی شرکاء میں شامل ہوں۔ یکساں ملک/شہر/ماڈل/رسائی کے پانچ قابلِ استعمال ٹیسٹ کے بعد گروہ ظاہر ہوگا۔",
      contribute: "ایک ٹیسٹ جمع کریں",
      headers: ["شہر / ملک", "بتایا گیا ماڈل", "رسائی", "ٹیسٹ", "استدلالی اسکور"],
      exploratory: "ابتدائی نتیجہ",
      descriptive: "یہ وضاحتی اوسط ہے؛ اعتماد کی حد نہیں دکھائی جاتی۔",
      scoreBasis: "core-2.0 میں اسکور ہر ٹیسٹ کے ۱۳ معروضی سوالات سے بنتا ہے؛ دو جائزے شامل نہیں۔",
      read: "یہ بات غور سے پڑھیں",
      interpretation: "فرق صرف رویّے میں تبدیلی کا ثبوت ہے، کسی مختلف پسِ پردہ ماڈل کا نہیں۔ صرف ایک ہی سروس، بتائے گئے ماڈل، رسائی، پلان اور بینچ مارک ورژن کا موازنہ کریں۔",
    },
    methodology: {
      eyebrow: "طریقۂ کار · صلاحیت کا پیمانہ",
      title: "ایک منضبط عوامی تجربہ، جو سب کی شرکت سے مضبوط ہوگا۔",
      lede: "بینچ مارک جانچتا ہے کہ شریک کی بتائی ہوئی جگہ کے لحاظ سے رویّہ بدلتا ہے یا نہیں، جبکہ سروس، ماڈل لیبل، پلان اور طریقۂ کار کو ممکن حد تک یکساں رکھا جاتا ہے۔",
      cards: [
        ["کیا ناپا جاتا ہے", "پندرہ ثقافتی طور پر غیر جانب دار سوال مشکل کی سیڑھی بناتے ہیں: ۱۳ معروضی اسکور شدہ سوال اور ماڈل کے تعارف و جواب کے انداز کے ۲ بغیر اسکور جائزے۔"],
        ["کیا محفوظ ہوتا ہے", "ملک/شہر، پروڈکٹ اور طریقۂ کار کی معلومات، سوالوں کی ترتیب اور قسم، مکمل جواب، اندازاً وقت، غیر مصدقہ ٹوکن خود بیان، اسکور اور اختیاری رائے۔"],
        ["کیا نجی رہتا ہے", "خام جواب عوامی نتائج میں نہیں آتے۔ نام، ای میل، اکاؤنٹ شناخت اور درست پتہ نہیں مانگے جاتے؛ شرکاء کو انہیں شامل نہ کرنے کی ہدایت ہے۔ خام IP کبھی محفوظ نہیں ہوتا اور صرف عارضی طور پر ناقابلِ ربط روزانہ HMAC انسدادِ غلط استعمال شمار میں بدلتا ہے۔"],
        ["اسکور کیسے بنتا ہے", "ورژن شدہ معروضی سرور اصول ۱۳ سوال اسکور کرتے ہیں؛ M1 اور M2 بغیر اسکور رہتے ہیں۔ عوامی گروہ کے لیے پانچ اندراج لازم ہیں اور تیس سے کم والے نتائج ابتدائی کہلاتے ہیں۔"],
      ],
      guidelinesEyebrow: "شرکاء کا طریقۂ کار",
      guidelinesTitle: "سب سے مفید جواب کے لیے ان اصولوں پر عمل کریں۔",
      guidelinesIntro: "حقیقت، کامل دکھائی دینے سے زیادہ اہم ہے۔ اگر کوئی حالت مختلف ہو تو سچ درج کریں؛ ٹیسٹ محفوظ اور نشان زد ہوگا، خاموشی سے تبدیل نہیں کیا جائے گا۔",
      guidelineGroups: [
        ["پہلے", ["پروڈکٹ میں دکھایا گیا درست ماڈل نام اور پلان استعمال کریں۔", "یادداشت/ذاتی ترتیب اور ذاتی ہدایات بند کریں۔", "VPN استعمال نہ کریں؛ اگر فعال ہو تو سچ بتائیں۔", "پروڈکٹ کا انگریزی UI استعمال کریں اور استدلال/تھنکنگ اختیار کی حالت درج کریں۔"]],
        ["دوران", ["ہر سوال کے لیے نئی چیٹ کھولیں۔", "کاپی بٹن استعمال کریں؛ سوال دوبارہ نہ لکھیں، بدلیں یا ترجمہ کریں۔", "صرف پہلا جواب لیں—دوبارہ جواب، ترمیم، ’کیا آپ کو یقین ہے؟‘ یا اگلا سوال نہیں۔", "نظر آنے والی سوچ اور REASONING TOKENS سطر سمیت پورا جواب جوں کا توں پیسٹ کریں۔", "اندازاً وقت درج کریں اور سب سوال ایک نشست میں مکمل کریں۔"]],
        ["بعد میں", ["اختیاری طور پر ۲۴–۴۸ گھنٹے بعد اسی ترتیب کے ساتھ پورا ٹیسٹ دہرائیں۔", "سوال یا جواب عوامی طور پر شائع یا زیرِ بحث نہ لائیں؛ جواب کا افشا آئندہ ڈیٹا آلودہ کرتا ہے۔"]],
      ],
      disqualifiersTitle: "محفوظ مگر بنیادی تجزیے سے خارج",
      disqualifiers: ["کوئی دوبارہ بنوایا گیا جواب", "جانچی گئی پروڈکٹ کا غیر انگریزی UI", "VPN کا استعمال یا اس کی نامعلوم حالت", "یادداشت/ذاتی ترتیب یا ذاتی ہدایات چالو یا نامعلوم", "ترجمہ شدہ سوال", "متعدد دنوں میں مکمل ہونے والا ٹیسٹ"],
      tokenNote: "ماڈل اپنے پوشیدہ استدلالی ٹوکن قابلِ اعتماد طور پر نہیں دیکھ سکتا۔ اس کا دیا ہوا ہر عدد غیر مصدقہ خود بیان ہے اور کبھی ناپا ہوا ٹوکن شمار نہیں بتایا جاتا۔",
      limits: "ثبوت کی حدود",
      limitsTitle: "یہ رجحان دکھا سکتا ہے، ارادہ ثابت نہیں کر سکتا۔",
      limitations: ["ملک اور شہر شریک خود بتاتا ہے اور تصدیق نہیں ہوتی۔", "شرکاء پوری آبادی کی نمائندگی نہیں کرتے۔", "خود کاپی پیسٹ کرنے میں غلطی ہو سکتی ہے۔", "ایک شخص ایک سے زیادہ بار حصہ لے سکتا ہے۔", "بلنگ کا ملک اور اکاؤنٹ کی سابقہ معلومات قابو میں نہیں۔", "سروس فراہم کرنے والے ماڈل بدلتے اور تجربے کرتے رہتے ہیں۔", "ماڈل ہر بار ایک جیسا جواب نہیں دیتے۔", "انگریزی سوال زبان اور علاقائی ترتیب سے متاثر ہو سکتے ہیں۔"],
      improve: "ثبوت بہتر بنانے میں مدد کریں",
      cta: "ہر احتیاط سے کیا گیا اور سچائی سے درج ٹیسٹ موازنے کو زیادہ مفید بناتا ہے۔",
      run: "بینچ مارک چلائیں",
    },
    footer: { left: "Reasoning Across Borders · آزاد عوامی بینچ مارک", right: "سائن اِن نہیں · خام IP محفوظ نہیں · صرف مجموعی نتائج" },
    errors: {
      results: "نتائج اس وقت دستیاب نہیں۔",
      location: "ملک منتخب کریں اور شہر یا قریب ترین بڑا شہر درج کریں؛ پتہ یا محلہ نہیں۔",
      fields: "سروس، ماڈل، رسائی اور پلان کی تمام معلومات مکمل کریں۔",
      protocol: "ہر ترتیبی خانے میں سچی قدر منتخب کریں۔",
      consent: "تصدیق کریں کہ آپ مطالعہ سمجھتے اور رضامند ہیں۔",
      session: "محفوظ بینچ مارک سیشن شروع نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
      save: "آپ کا اندراج محفوظ نہیں ہو سکا۔",
    },
    access: {
      Free: ["مفت", "کوئی باقاعدہ ادائیگی نہیں"],
      Paid: ["بامعاوضہ", "ذاتی، دفتری یا API کی ادائیگی"],
      "Not sure": ["معلوم نہیں", "پروڈکٹ میں یہ واضح نہیں"],
    },
    accessTypes: ["ذاتی مفت رسائی", "ذاتی بامعاوضہ رسائی", "تعلیمی یا تحقیقی رسائی", "دفتری یا ٹیم کی رسائی", "ادارے کی رسائی", "معلوم نہیں"],
    clarity: ["یہ سوال چھوڑ دیں", "بالکل غیر واضح", "اکثر غیر واضح", "کچھ واضح، کچھ مشکل", "زیادہ تر واضح", "بالکل واضح"],
    feedback: { "": "یہ سوال چھوڑ دیں", unclear: "سوال واضح نہیں تھا", "answer disputed": "درست جواب سے اختلاف", "technical issue": "تکنیکی مسئلہ", "too long": "سوال بہت لمبا" },
  },
} as const;

export const PROMPT_UI: Record<Language, Record<string, { capability: string; title: string }>> = {
  en: {
    A1: { capability: "Arithmetic reasoning", title: "Two-product calculation" },
    A2: { capability: "String transformation", title: "Reverse a string" },
    A3: { capability: "Deductive logic", title: "Category implication" },
    B1: { capability: "Quantitative reasoning", title: "Production and rework" },
    B2: { capability: "Instruction following", title: "Sentence constraints" },
    B3: { capability: "Probability", title: "Same-group probability" },
    B4: { capability: "Code reasoning", title: "List aliasing" },
    B5: { capability: "Constraint solving", title: "Unique ordering" },
    B6: { capability: "Premise correction", title: "Correct a false premise" },
    C1: { capability: "Multi-step arithmetic", title: "Running calculation" },
    C2: { capability: "Instruction following", title: "Paragraph constraints" },
    C3: { capability: "Combinatorics", title: "Increasing digits" },
    C4: { capability: "Evidence fidelity", title: "Incomplete observations" },
    M1: { capability: "Model self-report", title: "Model metadata" },
    M2: { capability: "Explanatory probe", title: "Daytime sky" },
  },
  ur: {
    A1: { capability: "حسابی استدلال", title: "دو حاصل ضرب کا حساب" },
    A2: { capability: "متنی تبدیلی", title: "عبارت الٹنا" },
    A3: { capability: "استنباطی منطق", title: "زمروں کا نتیجہ" },
    B1: { capability: "مقداری استدلال", title: "پیداوار اور دوبارہ کام" },
    B2: { capability: "ہدایات پر عمل", title: "جملوں کی پابندیاں" },
    B3: { capability: "امکان", title: "ایک ہی گروہ کا امکان" },
    B4: { capability: "کوڈ کی سمجھ", title: "فہرست کا مشترک حوالہ" },
    B5: { capability: "شرائط حل کرنا", title: "منفرد ترتیب" },
    B6: { capability: "مفروضہ درست کرنا", title: "غلط مفروضہ درست کریں" },
    C1: { capability: "کثیر مرحلہ حساب", title: "چلتا ہوا حساب" },
    C2: { capability: "ہدایات پر عمل", title: "پیراگراف کی پابندیاں" },
    C3: { capability: "ترکیبی شمار", title: "بڑھتے ہوئے ہندسے" },
    C4: { capability: "ثبوت سے وفاداری", title: "نامکمل مشاہدات" },
    M1: { capability: "ماڈل کا خود بیان", title: "ماڈل کی معلومات" },
    M2: { capability: "وضاحتی جائزہ", title: "دن کا آسمان" },
  },
};
