export type Language = "en" | "ur";

export const UI_COPY = {
  en: {
    brandSubtitle: "A public reasoning benchmark",
    nav: { aria: "Main navigation", contribute: "Contribute", results: "Results", methodology: "Methodology" },
    intro: {
      eyebrow: "Open public benchmark",
      headline: "Does the same AI reason differently depending on where you use it?",
      lede: "Run ten identical prompts through the model you already use, then contribute its complete responses anonymously.",
      start: "Start the benchmark",
      seeResults: "See public results",
      factsAria: "Benchmark details",
      facts: [
        ["≈ 10 min", "one prompt at a time"],
        ["Anonymous", "no account or email"],
        ["City only", "no GPS or IP stored"],
      ],
      heroAlt: "The same AI system receiving identical prompts from people in different cities and returning responses for comparison.",
      hypothesis: "The same declared model may still show different reasoning performance in different places.",
      disclaimer: "This measures observable differences. It does not prove intentional routing or hidden model substitution.",
      guideEyebrow: "How to take part",
      guideTitle: "Three simple actions",
      guideAlt: "A wordless guide showing a prompt copied from this benchmark, sent to an AI, and the complete response pasted back here.",
      guideSteps: ["Copy the prompt", "Ask your AI", "Paste the complete answer"],
    },
    setup: {
      eyebrow: "Before you begin",
      title: "Set up one comparable test.",
      lede: "Enter only what is visible in the AI product you are testing.",
      where: "Where are you?",
      cityLabel: "City or nearest large city",
      cityPlaceholder: "e.g. Lahore",
      cityNote: "Do not enter an address, neighborhood, postal code, or coordinates.",
      modelQuestion: "Which model are you testing?",
      providerLabel: "Provider or product",
      modelLabel: "Model label shown in the app",
      choose: "Choose one",
      exactModel: "Exact model label",
      exactPlaceholder: "Copy the label shown in your app",
      accessQuestion: "What access are you using?",
      planLabel: "Plan label or access type",
      planPlaceholder: "e.g. Plus, Pro, Team, API, Free",
      consentTitle: "I understand and want to contribute anonymously.",
      consentText: "The research record contains my city, model/access selections, pasted model responses, scores, benchmark version, and submission day—nothing that identifies my account.",
      continue: "Continue to instructions",
      privacyTitle: "Your city is the only location information you provide.",
      privacyItems: ["No name or email", "No sign-in or account ID", "No GPS request", "No IP address stored by this site", "No cookies, analytics, or fingerprinting"],
      privacyNote: "Network infrastructure may transiently process connection data, but this benchmark does not read or add it to the research database.",
    },
    runner: {
      yourTest: "Your test",
      rulesTitle: "Keep every run comparable",
      rules: ["Start a fresh chat for each prompt.", "Keep web, search, and tools off.", "Do not edit or translate.", "Use the first answer only.", "Paste the complete response."],
      question: "Question",
      of: "of",
      complete: "complete",
      fixedNotice: "For a fair comparison, this English prompt is fixed. Copy it exactly—do not edit or translate it.",
      copyPrompt: "Copy prompt",
      defaultStatus: "Copy this exactly, then paste the model’s first complete answer below.",
      copied: "Copied—paste it into a fresh chat with your selected AI model.",
      blocked: "Copy was blocked by your browser. Select the prompt text and copy it manually.",
      responseLabel: "Paste the complete model response",
      responsePlaceholder: "Paste the response here—including any explanation, refusal, or error message.",
      shortWarning: "This response is unusually short. A refusal or error is valid, but please paste it completely.",
      back: "Back",
      next: "Next question",
      review: "Review responses",
    },
    review: {
      eyebrow: "Final check",
      title: "Ready to contribute.",
      lede: "Your answers are scored on the server. Correct answers are not shown before submission.",
      record: "Benchmark record",
      city: "City",
      provider: "Provider",
      model: "Model",
      access: "Access",
      responses: "Responses",
      edit: "Edit setup",
      improve: "Help improve",
      feedback: "Optional structured feedback",
      clarity: "Were the prompts clear?",
      attention: "Which prompt needs attention?",
      none: "None / skip",
      why: "Why?",
      anonymous: "Anonymous by design",
      privateNote: "No raw response appears publicly. Groups are hidden until at least five matching contributions exist.",
      submitting: "Contributing…",
      submit: "Contribute anonymously",
    },
    success: {
      eyebrow: "Contribution received",
      title: "Your run is now part of the benchmark.",
      score: "objective reasoning score",
      privatePrefix: "Your raw model responses remain private. The aggregate for",
      privateSuffix: "will appear only after enough matching contributions meet the five-response privacy threshold.",
      results: "View aggregate results",
      home: "Return home",
    },
    results: {
      eyebrow: "Public aggregate",
      title: "Look for patterns, not rankings.",
      lede: "These comparisons show observed behavior under self-reported conditions. They do not prove that location caused the difference or that a provider substituted a model.",
      loading: "Loading aggregate results…",
      unavailable: "Results are not ready yet.",
      stats: ["eligible contributions", "self-reported cities", "declared models", "display threshold"],
      emptyTitle: "No comparison has reached the privacy threshold yet.",
      emptyText: "Be one of the first contributors. A city/model/access group appears after five eligible runs.",
      contribute: "Contribute a run",
      headers: ["City", "Declared model", "Access", "Runs", "Reasoning score"],
      exploratory: "exploratory",
      approx: "Approx. 95% interval",
      read: "Read this carefully",
      interpretation: "A difference is evidence of behavioral variation—not proof of a different backend model. Compare only the same provider, declared model, access type, plan, and benchmark version.",
    },
    methodology: {
      eyebrow: "Methodology · core benchmark",
      title: "A small experiment, made stronger together.",
      lede: "The benchmark asks whether objective reasoning performance is associated with a participant’s self-entered city when the declared model and access type are held constant.",
      cards: [
        ["What is measured", "Ten fixed tasks cover arithmetic, deduction, patterns, probability, instruction following, structured output, evidence fidelity, code, spatial reasoning, and logical inference."],
        ["What is stored", "City, selected provider/model/access, complete model outputs, derived scores, benchmark version, submission day, and optional structured prompt-quality feedback."],
        ["What stays private", "Raw model outputs never appear in public results. The site does not request or store names, emails, account identifiers, GPS, IP addresses, cookies, analytics identifiers, or device fingerprints."],
        ["How scoring works", "Answers are scored server-side against versioned objective criteria. Public cells require five eligible submissions; results below thirty remain explicitly exploratory."],
      ],
      limits: "Limits of the evidence",
      limitsTitle: "This can identify a pattern. It cannot establish intent.",
      limitations: ["City is self-reported and unverified.", "Participants are a convenience sample.", "Manual copying can introduce errors.", "People may contribute more than once.", "Billing region and account history remain uncontrolled.", "Providers update models and run experiments.", "Models are nondeterministic.", "English prompts may interact with locale settings."],
      improve: "Help improve the evidence",
      cta: "Every careful contribution makes the comparison more useful.",
      run: "Run the benchmark",
    },
    footer: { left: "Reasoning Across Borders · An independent, open benchmark", right: "No tracking · No sign-in · City only" },
    errors: { results: "Results are unavailable.", city: "Enter your city or nearest large city—not an address or neighborhood.", fields: "Complete the provider, model, access, and plan fields.", consent: "Confirm that you understand the anonymous contribution rules.", save: "Your contribution could not be saved." },
    access: {
      Free: ["Free", "No recurring payment"],
      Paid: ["Paid", "Personal, work, or API payment"],
      "Not sure": ["Not sure", "The product does not make this clear"],
    },
    accessTypes: ["Free individual access", "Paid individual access", "Education or research access", "Work or team access", "Enterprise access", "Not sure"],
    clarity: ["Skip this question", "Very unclear", "Often unclear", "Mixed", "Mostly clear", "Very clear"],
    feedback: { "": "Skip this question", unclear: "unclear", "answer disputed": "answer disputed", "technical issue": "technical issue", "too long": "too long" },
  },
  ur: {
    brandSubtitle: "سرحدوں کے پار سوچ",
    nav: { aria: "مرکزی فہرست", contribute: "حصہ لیں", results: "نتائج", methodology: "طریقۂ کار" },
    intro: {
      eyebrow: "عوام کے لیے کھلا بینچ مارک",
      headline: "کیا ایک ہی اے آئی مختلف جگہوں پر مختلف انداز سے سوچتا ہے؟",
      lede: "اپنے زیرِ استعمال ماڈل سے دس ایک جیسے سوالات پوچھیں، پھر اس کے مکمل جواب گمنام طور پر جمع کرائیں۔",
      start: "جانچ شروع کریں",
      seeResults: "عوامی نتائج دیکھیں",
      factsAria: "بینچ مارک کی تفصیل",
      facts: [["تقریباً ۱۰ منٹ", "ایک وقت میں ایک سوال"], ["مکمل گمنام", "اکاؤنٹ یا ای میل نہیں"], ["صرف شہر", "GPS یا IP محفوظ نہیں"]],
      heroAlt: "مختلف شہروں کے لوگ ایک ہی اے آئی نظام کو ایک جیسے سوال بھیج رہے ہیں اور ملنے والے جواب موازنے کے لیے واپس آ رہے ہیں۔",
      hypothesis: "ایپ میں دکھایا گیا ماڈل ایک ہی ہو، تب بھی مختلف جگہوں پر اس کی استدلالی کارکردگی بدل سکتی ہے۔",
      disclaimer: "یہ صرف نظر آنے والے فرق کو ناپتا ہے۔ یہ جان بوجھ کر مختلف ماڈل دینے یا پسِ پردہ ماڈل بدلنے کو ثابت نہیں کرتا۔",
      guideEyebrow: "حصہ لینے کا طریقہ",
      guideTitle: "صرف تین آسان کام",
      guideAlt: "بغیر الفاظ کی تصویر: سوال یہاں سے کاپی کریں، اے آئی سے پوچھیں، اور پورا جواب واپس یہاں پیسٹ کریں۔",
      guideSteps: ["سوال کاپی کریں", "اے آئی سے پوچھیں", "مکمل جواب پیسٹ کریں"],
    },
    setup: {
      eyebrow: "شروع کرنے سے پہلے",
      title: "ایک قابلِ موازنہ ٹیسٹ تیار کریں۔",
      lede: "صرف وہ معلومات درج کریں جو آپ کی اے آئی ایپ میں نظر آ رہی ہیں۔",
      where: "آپ کس شہر میں ہیں؟",
      cityLabel: "اپنا شہر یا قریب ترین بڑا شہر",
      cityPlaceholder: "مثلاً لاہور",
      cityNote: "گھر کا پتہ، محلہ، پوسٹل کوڈ یا نقشے کے نقاط درج نہ کریں۔",
      modelQuestion: "آپ کون سا ماڈل جانچ رہے ہیں؟",
      providerLabel: "اے آئی سروس یا پروڈکٹ",
      modelLabel: "ایپ میں دکھایا گیا ماڈل",
      choose: "ایک منتخب کریں",
      exactModel: "ماڈل کا بالکل درست نام",
      exactPlaceholder: "ایپ میں دکھایا گیا نام جوں کا توں لکھیں",
      accessQuestion: "آپ کس قسم کی رسائی استعمال کر رہے ہیں؟",
      planLabel: "پلان یا رسائی کی قسم",
      planPlaceholder: "مثلاً Plus، Pro، Team، API یا Free",
      consentTitle: "میں سمجھتا/سمجھتی ہوں اور گمنام طور پر حصہ لینا چاہتا/چاہتی ہوں۔",
      consentText: "تحقیقی ریکارڈ میں صرف میرا شہر، منتخب ماڈل اور رسائی، پیسٹ کیے گئے جواب، اسکور، بینچ مارک ورژن اور جمع کرانے کا دن شامل ہوگا۔ اکاؤنٹ کی شناخت کرنے والی کوئی چیز محفوظ نہیں ہوگی۔",
      continue: "ہدایات دیکھیں",
      privacyTitle: "جگہ کے بارے میں آپ صرف اپنے شہر کا نام دیتے ہیں۔",
      privacyItems: ["نام یا ای میل نہیں", "سائن اِن یا اکاؤنٹ ID نہیں", "GPS کی اجازت نہیں مانگی جاتی", "یہ ویب سائٹ IP ایڈریس محفوظ نہیں کرتی", "کوکیز، اینالیٹکس یا ڈیوائس فنگرپرنٹنگ نہیں"],
      privacyNote: "انٹرنیٹ کا بنیادی نظام رابطے کی معلومات کو عارضی طور پر استعمال کر سکتا ہے، لیکن یہ بینچ مارک انہیں پڑھتا یا تحقیقی ڈیٹابیس میں شامل نہیں کرتا۔",
    },
    runner: {
      yourTest: "آپ کا ٹیسٹ",
      rulesTitle: "ہر ٹیسٹ کو ایک جیسا رکھیں",
      rules: ["ہر سوال کے لیے نئی چیٹ شروع کریں۔", "ویب، سرچ اور دوسرے ٹولز بند رکھیں۔", "سوال کو نہ بدلیں اور نہ ترجمہ کریں۔", "صرف پہلا جواب استعمال کریں۔", "پورا جواب پیسٹ کریں۔"],
      question: "سوال",
      of: "از",
      complete: "مکمل",
      fixedNotice: "منصفانہ موازنے کے لیے یہ انگریزی سوال سب کے لیے ایک ہے۔ اسے جوں کا توں کاپی کریں—نہ بدلیں، نہ ترجمہ کریں۔",
      copyPrompt: "سوال کاپی کریں",
      defaultStatus: "اسے جوں کا توں کاپی کریں، پھر ماڈل کا پہلا مکمل جواب نیچے پیسٹ کریں۔",
      copied: "کاپی ہو گیا۔ اسے اپنے منتخب اے آئی ماڈل کی نئی چیٹ میں پیسٹ کریں۔",
      blocked: "براؤزر نے خودکار کاپی روک دی۔ سوال منتخب کر کے خود کاپی کریں۔",
      responseLabel: "ماڈل کا مکمل جواب پیسٹ کریں",
      responsePlaceholder: "پورا جواب یہاں پیسٹ کریں—وضاحت، انکار، یا غلطی کا پیغام بھی شامل کریں۔",
      shortWarning: "یہ جواب بہت مختصر لگ رہا ہے۔ انکار یا غلطی کا پیغام بھی درست اندراج ہے، لیکن اسے پورا پیسٹ کریں۔",
      back: "واپس",
      next: "اگلا سوال",
      review: "جوابات دیکھیں",
    },
    review: {
      eyebrow: "آخری جانچ",
      title: "آپ کا اندراج تیار ہے۔",
      lede: "جوابات کا اسکور سرور پر بنایا جاتا ہے۔ جمع کرانے سے پہلے درست جواب نہیں دکھائے جاتے۔",
      record: "بینچ مارک ریکارڈ",
      city: "شہر",
      provider: "سروس",
      model: "ماڈل",
      access: "رسائی",
      responses: "جوابات",
      edit: "معلومات بدلیں",
      improve: "بہتر بنانے میں مدد کریں",
      feedback: "اختیاری رائے",
      clarity: "کیا سوالات واضح تھے؟",
      attention: "کس سوال کو بہتر کرنے کی ضرورت ہے؟",
      none: "کوئی نہیں / چھوڑ دیں",
      why: "کیوں؟",
      anonymous: "شروع سے گمنامی کو ترجیح",
      privateNote: "کوئی اصل جواب عوام کو نہیں دکھایا جاتا۔ ایک جیسے کم از کم پانچ اندراج ہونے تک گروپ کے نتائج بھی نہیں دکھائے جاتے۔",
      submitting: "جمع ہو رہا ہے…",
      submit: "گمنام طور پر جمع کریں",
    },
    success: {
      eyebrow: "اندراج موصول ہو گیا",
      title: "آپ کا ٹیسٹ اب بینچ مارک کا حصہ ہے۔",
      score: "معروضی استدلال کا اسکور",
      privatePrefix: "آپ کے ماڈل کے اصل جواب نجی رہیں گے۔",
      privateSuffix: "کا مجموعی نتیجہ تب دکھایا جائے گا جب ایک جیسے کم از کم پانچ اندراج مکمل ہو جائیں۔",
      results: "مجموعی نتائج دیکھیں",
      home: "مرکزی صفحے پر واپس جائیں",
    },
    results: {
      eyebrow: "عوامی مجموعی نتائج",
      title: "رجحان دیکھیں، درجہ بندی نہیں۔",
      lede: "یہ موازنہ لوگوں کی اپنی بتائی ہوئی معلومات کے تحت نظر آنے والا رویہ دکھاتا ہے۔ اس سے یہ ثابت نہیں ہوتا کہ فرق جگہ کی وجہ سے آیا یا سروس نے ماڈل بدل دیا۔",
      loading: "مجموعی نتائج لوڈ ہو رہے ہیں…",
      unavailable: "نتائج ابھی تیار نہیں۔",
      stats: ["قابلِ استعمال اندراج", "بتائے گئے شہر", "بتائے گئے ماڈل", "دکھانے کی کم از کم حد"],
      emptyTitle: "ابھی کسی موازنے کے لیے گمنامی کی کم از کم حد پوری نہیں ہوئی۔",
      emptyText: "ابتدائی شرکاء میں شامل ہوں۔ ایک ہی شہر، ماڈل اور رسائی کے پانچ قابلِ استعمال ٹیسٹ مکمل ہونے پر گروپ دکھائی دے گا۔",
      contribute: "ایک ٹیسٹ جمع کریں",
      headers: ["شہر", "بتایا گیا ماڈل", "رسائی", "ٹیسٹ", "استدلالی اسکور"],
      exploratory: "ابتدائی نتیجہ",
      approx: "تقریباً 95٪ حد",
      read: "یہ بات غور سے پڑھیں",
      interpretation: "فرق صرف رویے میں تبدیلی کا ثبوت ہے، کسی مختلف پسِ پردہ ماڈل کا نہیں۔ صرف ایک ہی سروس، بتایا گیا ماڈل، رسائی، پلان اور بینچ مارک ورژن کا موازنہ کریں۔",
    },
    methodology: {
      eyebrow: "طریقۂ کار · بنیادی بینچ مارک",
      title: "ایک چھوٹا تجربہ، جو سب کی شرکت سے مضبوط ہوگا۔",
      lede: "یہ بینچ مارک جانچتا ہے کہ ایک ہی بتائے گئے ماڈل اور رسائی کے تحت، استدلالی کارکردگی کا تعلق شریک کے درج کردہ شہر سے نظر آتا ہے یا نہیں۔",
      cards: [
        ["کیا ناپا جاتا ہے", "دس مقررہ سوالات حساب، منطق، ترتیب، امکان، ہدایات پر عمل، منظم معلومات، عبارت، کوڈ، سمت اور منطقی نتیجے کو جانچتے ہیں۔"],
        ["کیا محفوظ ہوتا ہے", "شہر، منتخب سروس، ماڈل اور رسائی، ماڈل کے مکمل جواب، اسکور، بینچ مارک ورژن، جمع کرانے کا دن، اور سوالات پر اختیاری رائے۔"],
        ["کیا نجی رہتا ہے", "اصل جواب عوامی نتائج میں کبھی نہیں دکھائے جاتے۔ سائٹ نام، ای میل، اکاؤنٹ شناخت، GPS، IP، کوکیز، اینالیٹکس شناخت یا ڈیوائس فنگرپرنٹ محفوظ نہیں کرتی۔"],
        ["اسکور کیسے بنتا ہے", "جوابات کو سرور پر معروضی اصولوں سے جانچا جاتا ہے۔ عوامی نتیجے کے لیے کم از کم پانچ اندراج ضروری ہیں؛ تیس سے کم اندراج والے نتائج ابتدائی ہیں۔"],
      ],
      limits: "اس ثبوت کی حدود",
      limitsTitle: "یہ کسی رجحان کی نشاندہی کر سکتا ہے، ارادہ ثابت نہیں کر سکتا۔",
      limitations: ["شہر شریک خود بتاتا ہے؛ اس کی تصدیق نہیں ہوتی۔", "شرکاء مکمل آبادی کی نمائندگی نہیں کرتے۔", "خود کاپی پیسٹ کرنے میں غلطی ہو سکتی ہے۔", "ایک شخص ایک سے زیادہ بار حصہ لے سکتا ہے۔", "بلنگ کا ملک اور اکاؤنٹ کی سابقہ معلومات قابو میں نہیں ہیں۔", "سروس فراہم کرنے والے ماڈل بدلتے اور تجربے کرتے رہتے ہیں۔", "ماڈل ہر بار ایک جیسا جواب نہیں دیتے۔", "انگریزی سوالات پر زبان اور علاقائی سیٹنگز اثر انداز ہو سکتی ہیں۔"],
      improve: "ثبوت بہتر بنانے میں مدد کریں",
      cta: "ہر احتیاط سے کیا گیا اندراج اس موازنے کو زیادہ مفید بناتا ہے۔",
      run: "بینچ مارک چلائیں",
    },
    footer: { left: "Reasoning Across Borders · ایک آزاد، عوامی بینچ مارک", right: "کوئی ٹریکنگ نہیں · کوئی سائن اِن نہیں · صرف شہر" },
    errors: { results: "نتائج اس وقت دستیاب نہیں۔", city: "اپنا شہر یا قریب ترین بڑا شہر درج کریں؛ پتہ یا محلہ نہیں۔", fields: "سروس، ماڈل، رسائی اور پلان کی تمام معلومات مکمل کریں۔", consent: "تصدیق کریں کہ آپ گمنام شرکت کے اصول سمجھتے ہیں۔", save: "آپ کا اندراج محفوظ نہیں ہو سکا۔" },
    access: {
      Free: ["مفت", "کوئی باقاعدہ ادائیگی نہیں"],
      Paid: ["بامعاوضہ", "ذاتی، دفتری یا API کی ادائیگی"],
      "Not sure": ["معلوم نہیں", "ایپ میں یہ واضح نہیں"],
    },
    accessTypes: ["ذاتی مفت رسائی", "ذاتی بامعاوضہ رسائی", "تعلیمی یا تحقیقی رسائی", "دفتری یا ٹیم کی رسائی", "ادارے کی رسائی", "معلوم نہیں"],
    clarity: ["یہ سوال چھوڑ دیں", "بالکل غیر واضح", "اکثر غیر واضح", "کچھ واضح، کچھ مشکل", "زیادہ تر واضح", "بالکل واضح"],
    feedback: { "": "یہ سوال چھوڑ دیں", unclear: "سوال واضح نہیں تھا", "answer disputed": "درست جواب سے اختلاف ہے", "technical issue": "تکنیکی مسئلہ آیا", "too long": "سوال بہت لمبا تھا" },
  },
} as const;

export const PROMPT_UI: Record<Language, Record<string, { capability: string; title: string }>> = {
  en: {
    "arithmetic-01": { capability: "Arithmetic reasoning", title: "Inventory calculation" },
    "logic-01": { capability: "Deductive logic", title: "Pet ownership" },
    "pattern-01": { capability: "Pattern reasoning", title: "Sequence rule" },
    "probability-01": { capability: "Probabilistic reasoning", title: "Two draws" },
    "constraint-01": { capability: "Instruction following", title: "Exact constraints" },
    "json-01": { capability: "Structured reasoning", title: "JSON extraction" },
    "evidence-01": { capability: "Evidence fidelity", title: "Reasoning from a passage" },
    "code-01": { capability: "Code reasoning", title: "Order-preserving deduplication" },
    "spatial-01": { capability: "Spatial reasoning", title: "Grid movement" },
    "inference-01": { capability: "Logical inference", title: "What follows?" },
  },
  ur: {
    "arithmetic-01": { capability: "حسابی استدلال", title: "سامان کا حساب" },
    "logic-01": { capability: "منطقی نتیجہ اخذ کرنا", title: "پالتو جانوروں کی ملکیت" },
    "pattern-01": { capability: "ترتیب پہچاننا", title: "ترتیب کا اصول" },
    "probability-01": { capability: "امکان کا استدلال", title: "دو بار انتخاب" },
    "constraint-01": { capability: "ہدایات پر عمل", title: "درست شرائط" },
    "json-01": { capability: "منظم معلومات", title: "JSON میں معلومات" },
    "evidence-01": { capability: "متن سے درست جواب", title: "عبارت سے جواب" },
    "code-01": { capability: "کوڈ کی سمجھ", title: "ترتیب برقرار رکھتے ہوئے تکرار ختم کرنا" },
    "spatial-01": { capability: "سمتی استدلال", title: "گرڈ پر حرکت" },
    "inference-01": { capability: "منطقی نتیجہ", title: "کیا نتیجہ نکلتا ہے؟" },
  },
};

